sudo: false
language: C
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
script:
- sudo apt-get install -y maven
- mvn test
deploy:
  provider: script
  script:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - mvn deploy
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - julio@packagecloud.io
    on_success: change
    on_failure: always
